#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#    The name of the custom HTTP header must be X-Served-By
#    The value of the custom HTTP header must be the hostname of the server Nginx is running on

# update and install nginx
apt-get update
apt-get install -y nginx

# copy the new_default file into sites available directorie
cp new_default_1 /etc/nginx/sites-available/default

# check the syntax and restart the service
nginx -t
sudo /etc/init.d/nginx restart
