#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

sudo apt-get update
sudo apt-get install -y haproxy

sudo cp haproxy_default /etc/haproxy/haproxy.cfg
sudo service haproxy restart
