#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

sudo apt-get update
sudo apt-get install -y haproxy
cp haproxy_default /etc/haproxy/haproxy.cfg
text="
frontend first_frontend
    bind :80
    default_backend web_servers
    
backend web_servers
    balance roundrobin
    server web-01 54.227.49.160
    server web-02 3.88.139.128"

sudo service haproxy restart
