#!/usr/bin/env bash
# script that displays numbers from 1 to 100 but using FizzBuzz
FILE=/etc/passwd
while read -r p
do
	cut -d: -f1 <<<"$p" | tr -d $'\n'
	echo -n :
	cut -d: -f3 <<<"$p" | tr -d $'\n'
	echo -n :
	cut -d: -f6 <<<"$p" | tr -d $'\n'
	echo
done <$FILE
