#!/usr/bin/env bash
# script that displays numbers from 1 to 100 but using FizzBuzz
FILE=/etc/passwd
while read -r p
do
	echo -n "The user "
	cut -d: -f1 <<<"$p" | tr -d $'\n'
	echo -n " is part of the "
	cut -d: -f4 <<<"$p" | tr -d $'\n'
	echo -n " gang, lives in "
	cut -d: -f6 <<<"$p" | tr -d $'\n'
	echo -n " and rides "
	cut -d: -f7 <<<"$p" | tr -d $'\n'
	echo -n ". "
	cut -d: -f7 <<<"$p" | tr -d $'\n'
	echo -n " place is protected by the passcode "
	cut -d: -f2 <<<"$p" | tr -d $'\n'
	echo -n ", more info about the user here: "
	cut -d: -f5 <<<"$p" | tr -d $'\n'
	echo
done <$FILE
